thr:
	g++ -Wall -lzmq -o remote_thr remote_thr.cpp
	g++ -Wall -lzmq -o local_thr local_thr.cpp
lat:
	g++ -Wall -lzmq -o remote_lat remote_lat.cpp
	g++ -Wall -lzmq -o local_lat local_lat.cpp
clean:
	rm *.o remote_lat remote_thr local_lat local_thr
